### ISSUE TITLE
ScheduleService.consulCustomData的值是取的哪里的？

### ISSUE THREAD

**Issue by WTNameIsOk** [nest-cloud/nestcloud-starter#6]
https://github.com/nest-cloud/nestcloud-starter/blob/4bde1ca2d1ed385a717b2144cdcef096020e3a6d/src/services/ScheduleService.ts#L14-L17
https://github.com/nest-cloud/nestcloud-starter/blob/4bde1ca2d1ed385a717b2144cdcef096020e3a6d/src/bootstrap-development.yml#L11

consul key 新增KV 'config__nestcloud-starter-service__development','nestcloud-starter-service-config' 获取不到，值一直都是 default custom data，项目文件中也没有找到类似的key

**Comment by miaowing** [comment]
Consul KV 中插入如下数据：
<img width="663" alt="image" src="https://user-images.githubusercontent.com/12780562/65144324-b4112100-da49-11e9-8032-edee5291ed0e.png">

**Comment by WTNameIsOk** [comment]
> Consul KV中插入如下数据：
> <img alt="图片" width="663" src="https://user-images.githubusercontent.com/12780562/65144324-b4112100-da49-11e9-8032-edee5291ed0e.png">

感谢

**Comment by WTNameIsOk** [comment]
如图设置值后，会导致ConsulConfigModule不能初始化

**Comment by WTNameIsOk** [comment]
清空值后，可以正常运行

**Comment by miaowing** [comment]
```yaml
custom:
  data: test
```
Sorry，custom 后边少了个冒号，YAML格式不正确，不能解析

**Comment by WTNameIsOk** [comment]
no，我带了冒号的

**Comment by WTNameIsOk** [comment]
sorry,编辑器的格式原因
