### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by WTNameIsOk** [nest-cloud/nestcloud-starter#7]
https://github.com/nest-cloud/nestcloud-starter/blob/4bde1ca2d1ed385a717b2144cdcef096020e3a6d/src/services/ScheduleService.ts#L31
https://github.com/nest-cloud/nestcloud-starter/blob/4bde1ca2d1ed385a717b2144cdcef096020e3a6d/src/services/ScheduleService.ts#L36
https://github.com/nest-cloud/nestcloud-starter/blob/4bde1ca2d1ed385a717b2144cdcef096020e3a6d/src/services/ScheduleService.ts#L41

this.logger.log(level, msg)方法只会打印出level，msg丢失。
在这里我用console.log()替代了this.logger.log(level, msg)，可以成功输出值

**Comment by miaowing** [comment]
感谢，logger 目前换成 @nestjs/common 内置的 Logger，接口有调整，starter未及时修改导致

**Comment by WTNameIsOk** [comment]
最近在关注nestcloud，谢谢采纳

**Comment by miaowing** [comment]
Starter 已更新到 version 0.5.0-9，部分模块名称有修改
